export { default as CalendarPage } from './Calendar'
export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as Phonebook } from './Phonebook'
export { default as Profile } from './Profile'
export { default as Reminder } from './Reminder'
export { default as Associates } from './Associates'
